### ISSUE TITLE
mworks is broken

### ISSUE THREAD

**Issue by BonusPlay** [CERT-Polska/karton-dashboard#21]
Due to how mworks operates, `/docz` endpoint (available as button on navbar) is broken, as no `README.md` is available in docker container.
Same goes for nested routes (`/docs/doc/*`) as they expect markdown files in `/docs` directory.
There is also path traversal in `/docs/doc` endpoint (it requires file to end with `.md` though).

**Comment by nazywam** [comment]
Closed by #23?

**Comment by BonusPlay** [comment]
Yes.

**Comment by ITAYC0HEN** [comment]
can you release a new version that fixes this on pypi? I still have this issue on the release
