### ISSUE TITLE
grafana dashboard 

### ISSUE THREAD

**Issue by dor15** [CERT-Polska/karton-dashboard#49]
Hi all,
I run the karton dashboard with docker .
I would like to add metric to grafana and I'm not sure how to config the data source in Grafana.
I see the logs under /varz.

what is the URL and port that I should fill when I config the data source in grafana? 
thanks

**Comment by nazywam** [comment]
I think you should just point prometheus to the `/varz` endpoint. I.E. set the data source url to 'https://your-karton-dashboard/varz'

**Comment by dor15** [comment]
I'm getting Error reading Prometheus: client_error: client error: 404

![image](https://user-images.githubusercontent.com/32598575/147736353-cf5692e0-5b15-471a-8fd7-c8faeeff5389.png)

**Comment by nazywam** [comment]
That's weird :thinking:, can you see the request in karton-dashboard logs? Are you sure you're running the correct version of karton-dashboard?

**Comment by dor15** [comment]
we have the latest version of karton-dash.
I see the logs in /varz but for some reason when I'm trying to config the DS (Prometheus) in Grafana I got this error.
we run grafana from docker and for making sure there is no connectivity issue, I connected to docker and run curl to the same URL I've tried to config and got the logs, for example:

`
bash-5.1curl http://karton-dashboard.training.cprgit.com/varz
karton_tasks{name="karton_reporter",priority="high",status="Declared"} 0.0
karton_tasks{name="karton_reporter",priority="high",status="Spawned"} 0.0
karton_tasks{name="karton_reporter",priority="high",status="Started"} 0.0
karton_tasks{name="karton_reporter",priority="high",status="Finished"} 0.0
karton_tasks{name="karton_reporter",priority="high",status="Crashed"} 0.0
karton_tasks{name="karton_reporter",priority="normal",status="Declared"} 0.0
karton_tasks{name="karton_reporter",priority="normal",status="Spawned"} 2072.0
karton_tasks{name="karton_reporter",priority="normal",status="Started"} 37.0
karton_tasks{name="karton_reporter",priority="normal",status="Finished"} 0.0
karton_tasks{name="karton_reporter",priority="normal",status="Crashed"} 0.0
karton_tasks{name="karton_reporter",priority="low",status="Declared"} 0.0
karton_tasks{name="karton_reporter",priority="low",status="Spawned"} 0.0
karton_tasks{name="karton_reporter",priority="low",status="Started"} 0.0
karton_tasks{name="karton_reporter",priority="low",status="Finished"} 0.0
karton_tasks{name="karton_reporter",priority="low",status="Crashed"} 0.0
karton_tasks{name="karton_extractor",priority="high",status="Declared"} 0.0
karton_tasks{name="karton_extractor",priority="high",status="Spawned"} 0.0
karton_tasks{name="karton_extractor",priority="high",status="Started"} 0.0
karton_tasks{name="karton_extractor",priority="high",status="Finished"} 0.0
karton_tasks{name="karton_extractor",priority="high",status="Crashed"} 0.0
karton_tasks{name="karton_extractor",priority="normal",status="Declared"} 0.0
karton_tasks{name="karton_extractor",priority="normal",status="Spawned"} 0.0
karton_tasks{name="karton_extractor",priority="normal",status="Started"} 0.0
karton_tasks{name="karton_extractor",priority="normal",status="Finished"} 0.0
karton_tasks{name="karton_extractor",priority="normal",status="Crashed"} 0.0
karton_tasks{name="karton_extractor",priority="low",status="Declared"} 0.0
karton_tasks{name="karton_extractor",priority="low",status="Spawned"} 0.0
karton_tasks{name="karton_extractor",priority="low",status="Started"} 0.0
karton_tasks{name="karton_extractor",priority="low",status="Finished"} 0.0
karton_tasks{name="karton_extractor",priority="low",status="Crashed"} 0.0
karton_tasks{name="karton_classifier",priority="high",status="Declared"} 0.0
karton_tasks{name="karton_classifier",priority="high",status="Spawned"} 0.0
karton_tasks{name="karton_classifier",priority="high",status="Started"} 0.0
karton_tasks{name="karton_classifier",priority="high",status="Finished"} 0.0
karton_tasks{name="karton_classifier",priority="high",status="Crashed"} 0.0
karton_tasks{name="karton_classifier",priority="normal",status="Declared"} 0.0
karton_tasks{name="karton_classifier",priority="normal",status="Spawned"} 0.0
karton_tasks{name="karton_classifier",priority="normal",status="Started"} 0.0
karton_tasks{name="karton_classifier",priority="normal",status="Finished"} 0.0
karton_tasks{name="karton_classifier",priority="normal",status="Crashed"} 0.0
karton_tasks{name="karton_classifier",priority="low",status="Declared"} 0.0
karton_tasks{name="karton_classifier",priority="low",status="Spawned"} 0.0
karton_tasks{name="karton_classifier",priority="low",status="Started"} 0.0
karton_tasks{name="karton_classifier",priority="low",status="Finished"} 0.0
karton_tasks{name="karton_classifier",priority="low",status="Crashed"} 0.0`


logs from docker:
`
t=2021-12-30T09:59:16+0000 lvl=eror msg="Instant query failed" logger=tsdb.prometheus query=1+1 err="client_error: client error: 404"
t=2021-12-30T09:59:16+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/ds/query status=400 remote_addr=77.126.184.153 time_ms=1054 size=65 referer=http://54.77.213.22:3000/datasources/edit/_LjxkH0nz/
`

**Comment by dor15** [comment]
error from karton-dasboard logs:
`

INFO:werkzeug:10.0.1.217 - - [30/Dec/2021 14:34:23] "[33mPOST /varz/api/v1/query HTTP/1.1[0m" 404 -
--

`

**Comment by nazywam** [comment]
Seems like a simple misconfiguration.

Setup the endpoint host using https://prometheus.io/docs/introduction/first_steps/

And remember to set the `metrics_path` to `/varz` instead of the default `/metrics`: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config

**Comment by dor15** [comment]
you're right, my Prometheus configuration was totally messed up🙈😳 
thank you!
