### ISSUE TITLE
Karton v4.4.0 isn't compatible with task cancelling

### ISSUE THREAD

**Issue by JohnConnorRF** [CERT-Polska/karton-dashboard#55]
Since the update to [set_task_status ](https://github.com/CERT-Polska/karton/blob/master/karton/core/backend.py#L293) removed the consumer argument, the dashboard can no longer cancel tasks. 

This line [here](https://github.com/CERT-Polska/karton-dashboard/blob/master/karton/dashboard/app.py#L52) fails.

Would you mind updating this to support karton 4.4.0?

**Comment by psrok1** [comment]
Hi! It will be fixed as a part of https://github.com/CERT-Polska/karton-dashboard/pull/56 (it triggered typing checks)
